<?php

namespace ContainerSJAoR62;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Hydra_Processor_Link_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.hydra.processor.link.inner' shared service.
     *
     * @return \ApiPlatform\State\Processor\RespondProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/HttpResponseHeadersTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/HttpResponseStatusTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/RespondProcessor.php';

        $container->privates['api_platform.hydra.processor.link.inner'] = $instance = new \ApiPlatform\State\Processor\RespondProcessor(($container->privates['api_platform.symfony.iri_converter'] ?? self::getApiPlatform_Symfony_IriConverterService($container)), ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)), ($container->privates['api_platform.metadata.operation.metadata_factory'] ?? self::getApiPlatform_Metadata_Operation_MetadataFactoryService($container)));

        if ($container->has('debug.stopwatch')) {
            $instance->setStopwatch(($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
        }

        return $instance;
    }
}
