<?php

namespace ContainerSJAoR62;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Hydra_JsonSchema_SchemaFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.hydra.json_schema.schema_factory' shared service.
     *
     * @return \ApiPlatform\Hydra\JsonSchema\SchemaFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/SchemaFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/SchemaFactoryAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/ResourceMetadataTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/SchemaUriPrefixTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/hydra/JsonSchema/SchemaFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/DefinitionNameFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/DefinitionNameFactory.php';

        $a = ($container->privates['api_platform.hydra.json_schema.schema_factory.inner'] ?? $container->load('getApiPlatform_Hydra_JsonSchema_SchemaFactory_InnerService'));

        if (isset($container->privates['api_platform.hydra.json_schema.schema_factory'])) {
            return $container->privates['api_platform.hydra.json_schema.schema_factory'];
        }
        $b = ($container->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService($container));

        if (isset($container->privates['api_platform.hydra.json_schema.schema_factory'])) {
            return $container->privates['api_platform.hydra.json_schema.schema_factory'];
        }

        return $container->privates['api_platform.hydra.json_schema.schema_factory'] = new \ApiPlatform\Hydra\JsonSchema\SchemaFactory($a, $container->parameters['api_platform.serializer.default_context'], ($container->privates['api_platform.json_schema.definition_name_factory'] ??= new \ApiPlatform\JsonSchema\DefinitionNameFactory()), $b);
    }
}
