<?php

namespace ContainerSJAoR62;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangePasswordProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Processor\User\ChangePasswordProcessor' shared autowired service.
     *
     * @return \App\Processor\User\ChangePasswordProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Processor/User/ChangePasswordProcessor.php';

        return $container->privates['App\\Processor\\User\\ChangePasswordProcessor'] = new \App\Processor\User\ChangePasswordProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
