<?php

namespace ContainerSJAoR62;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordRequestProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Processor\User\ResetPasswordRequestProcessor' shared autowired service.
     *
     * @return \App\Processor\User\ResetPasswordRequestProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Processor/User/ResetPasswordRequestProcessor.php';

        return $container->privates['App\\Processor\\User\\ResetPasswordRequestProcessor'] = new \App\Processor\User\ResetPasswordRequestProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
