api_platform:
    title: 'Laundry Free API'
    description: 'RESTful API for Laundry Free Application'
    version: '1.0.0'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
