<?php

namespace ContainerD6uE35j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProcessor_WriteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.state_processor.write' shared service.
     *
     * @return \ApiPlatform\State\Processor\WriteProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/WriteProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/SerializeProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/http-cache/State/AddHeadersProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/AddLinkHeaderProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/CorsTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/hydra/State/HydraLinkProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/HttpResponseHeadersTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/HttpResponseStatusTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/RespondProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/CallableProcessor.php';

        $a = new \ApiPlatform\State\Processor\RespondProcessor(($container->privates['api_platform.symfony.iri_converter'] ?? self::getApiPlatform_Symfony_IriConverterService($container)), ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)), ($container->privates['api_platform.metadata.operation.metadata_factory'] ?? self::getApiPlatform_Metadata_Operation_MetadataFactoryService($container)));

        $b = ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true));

        if ($container->has('debug.stopwatch')) {
            $a->setStopwatch($b);
        }

        $c = new \ApiPlatform\State\Processor\AddLinkHeaderProcessor(new \ApiPlatform\Hydra\State\HydraLinkProcessor($a, ($container->privates['api_platform.router'] ?? self::getApiPlatform_RouterService($container))));
        if ($container->has('debug.stopwatch')) {
            $c->setStopwatch($b);
        }

        $d = new \ApiPlatform\State\Processor\SerializeProcessor(new \ApiPlatform\HttpCache\State\AddHeadersProcessor($c, true, NULL, NULL, $container->parameters['api_platform.http_cache.vary'], NULL, NULL, NULL), ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)), ($container->privates['api_platform.openapi.serializer_context_builder'] ?? $container->load('getApiPlatform_Openapi_SerializerContextBuilderService')));
        if ($container->has('debug.stopwatch')) {
            $d->setStopwatch($b);
        }

        $container->privates['api_platform.state_processor.write'] = $instance = new \ApiPlatform\State\Processor\WriteProcessor($d, new \ApiPlatform\State\CallableProcessor(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor' => ['privates', 'api_platform.doctrine.orm.state.persist_processor', 'getApiPlatform_Doctrine_Orm_State_PersistProcessorService', true],
            'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor' => ['privates', 'api_platform.doctrine.orm.state.remove_processor', 'getApiPlatform_Doctrine_Orm_State_RemoveProcessorService', true],
            'ApiPlatform\\Symfony\\Messenger\\Processor' => ['privates', 'ApiPlatform\\Symfony\\Messenger\\Processor', 'getProcessorService', true],
            'App\\Processor\\Area\\AreaCreateProcessor' => ['privates', 'App\\Processor\\Area\\AreaCreateProcessor', 'getAreaCreateProcessorService', true],
            'App\\Processor\\User\\ChangePasswordProcessor' => ['privates', 'App\\Processor\\User\\ChangePasswordProcessor', 'getChangePasswordProcessorService', true],
            'App\\Processor\\User\\ProfileProcessor' => ['privates', 'App\\Processor\\User\\ProfileProcessor', 'getProfileProcessorService', true],
            'App\\Processor\\User\\RegisterProcessor' => ['privates', 'App\\Processor\\User\\RegisterProcessor', 'getRegisterProcessorService', true],
            'App\\Processor\\User\\ResendVerificationProcessor' => ['privates', 'App\\Processor\\User\\ResendVerificationProcessor', 'getResendVerificationProcessorService', true],
            'App\\Processor\\User\\ResetPasswordConfirmProcessor' => ['privates', 'App\\Processor\\User\\ResetPasswordConfirmProcessor', 'getResetPasswordConfirmProcessorService', true],
            'App\\Processor\\User\\ResetPasswordRequestProcessor' => ['privates', 'App\\Processor\\User\\ResetPasswordRequestProcessor', 'getResetPasswordRequestProcessorService', true],
            'App\\Processor\\User\\VerifyProcessor' => ['privates', 'App\\Processor\\User\\VerifyProcessor', 'getVerifyProcessorService', true],
            'api_platform.doctrine.orm.state.persist_processor' => ['privates', 'api_platform.doctrine.orm.state.persist_processor', 'getApiPlatform_Doctrine_Orm_State_PersistProcessorService', true],
            'api_platform.doctrine.orm.state.remove_processor' => ['privates', 'api_platform.doctrine.orm.state.remove_processor', 'getApiPlatform_Doctrine_Orm_State_RemoveProcessorService', true],
            'api_platform.swagger_ui.processor' => ['privates', 'api_platform.swagger_ui.processor', 'getApiPlatform_SwaggerUi_ProcessorService', true],
        ], [
            'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor' => 'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor',
            'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor' => 'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor',
            'ApiPlatform\\Symfony\\Messenger\\Processor' => 'ApiPlatform\\Symfony\\Messenger\\Processor',
            'App\\Processor\\Area\\AreaCreateProcessor' => 'App\\Processor\\Area\\AreaCreateProcessor',
            'App\\Processor\\User\\ChangePasswordProcessor' => 'App\\Processor\\User\\ChangePasswordProcessor',
            'App\\Processor\\User\\ProfileProcessor' => 'App\\Processor\\User\\ProfileProcessor',
            'App\\Processor\\User\\RegisterProcessor' => 'App\\Processor\\User\\RegisterProcessor',
            'App\\Processor\\User\\ResendVerificationProcessor' => 'App\\Processor\\User\\ResendVerificationProcessor',
            'App\\Processor\\User\\ResetPasswordConfirmProcessor' => 'App\\Processor\\User\\ResetPasswordConfirmProcessor',
            'App\\Processor\\User\\ResetPasswordRequestProcessor' => 'App\\Processor\\User\\ResetPasswordRequestProcessor',
            'App\\Processor\\User\\VerifyProcessor' => 'App\\Processor\\User\\VerifyProcessor',
            'api_platform.doctrine.orm.state.persist_processor' => 'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor',
            'api_platform.doctrine.orm.state.remove_processor' => 'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor',
            'api_platform.swagger_ui.processor' => 'ApiPlatform\\Symfony\\Bundle\\SwaggerUi\\SwaggerUiProcessor',
        ])));

        if ($container->has('debug.stopwatch')) {
            $instance->setStopwatch($b);
        }

        return $instance;
    }
}
