<?php

namespace ContainerD6uE35j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_UriVariables_Transformer_ApiResourceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.uri_variables.transformer.api_resource' shared service.
     *
     * @return \ApiPlatform\Metadata\UriVariableTransformer\ApiResourceUriVariableTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/UriVariableTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/UriVariableTransformer/ApiResourceUriVariableTransformer.php';

        return $container->privates['api_platform.uri_variables.transformer.api_resource'] = new \ApiPlatform\Metadata\UriVariableTransformer\ApiResourceUriVariableTransformer(($container->privates['api_platform.api.identifiers_extractor'] ?? self::getApiPlatform_Api_IdentifiersExtractorService($container)), ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)));
    }
}
