<?php

namespace ContainerD6uE35j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAreaPostcodesProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Provider\Area\AreaPostcodesProvider' shared autowired service.
     *
     * @return \App\Provider\Area\AreaPostcodesProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Provider/Area/AreaPostcodesProvider.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Provider\\Area\\AreaPostcodesProvider'])) {
            return $container->privates['App\\Provider\\Area\\AreaPostcodesProvider'];
        }

        return $container->privates['App\\Provider\\Area\\AreaPostcodesProvider'] = new \App\Provider\Area\AreaPostcodesProvider($a);
    }
}
