<?php

namespace ContainerD6uE35j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Processor\User\RegisterProcessor' shared autowired service.
     *
     * @return \App\Processor\User\RegisterProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Processor/User/RegisterProcessor.php';

        return $container->privates['App\\Processor\\User\\RegisterProcessor'] = new \App\Processor\User\RegisterProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));
    }
}
