<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Area extends \App\Entity\Area implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'postcodes' => [parent::class, 'postcodes', null, 16],
        "\0".parent::class."\0".'timeSlots' => [parent::class, 'timeSlots', null, 16],
        'area' => [parent::class, 'area', null, 4],
        'createdAt' => [parent::class, 'createdAt', null, 4],
        'id' => [parent::class, 'id', null, 4],
        'postcodes' => [parent::class, 'postcodes', null, 16],
        'timeSlots' => [parent::class, 'timeSlots', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 4],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
