<?php

namespace Container871dO5O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProcessor_AddLinkHeaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.state_processor.add_link_header' shared service.
     *
     * @return \ApiPlatform\State\Processor\AddLinkHeaderProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/AddLinkHeaderProcessor.php';

        $container->privates['api_platform.state_processor.add_link_header'] = $instance = new \ApiPlatform\State\Processor\AddLinkHeaderProcessor(($container->privates['api_platform.hydra.processor.link'] ?? $container->load('getApiPlatform_Hydra_Processor_LinkService')));

        if ($container->has('debug.stopwatch')) {
            $instance->setStopwatch(($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
        }

        return $instance;
    }
}
