<?php

namespace Container871dO5O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProcessor_LocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.state_processor.locator' shared service.
     *
     * @return \ApiPlatform\State\CallableProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/CallableProcessor.php';

        return $container->privates['api_platform.state_processor.locator'] = new \ApiPlatform\State\CallableProcessor(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor' => ['privates', 'api_platform.doctrine.orm.state.persist_processor', 'getApiPlatform_Doctrine_Orm_State_PersistProcessorService', true],
            'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor' => ['privates', 'api_platform.doctrine.orm.state.remove_processor', 'getApiPlatform_Doctrine_Orm_State_RemoveProcessorService', true],
            'ApiPlatform\\Symfony\\Messenger\\Processor' => ['privates', 'ApiPlatform\\Symfony\\Messenger\\Processor', 'getProcessorService', true],
            'App\\Processor\\User\\ChangePasswordProcessor' => ['privates', 'App\\Processor\\User\\ChangePasswordProcessor', 'getChangePasswordProcessorService', true],
            'App\\Processor\\User\\ProfileProcessor' => ['privates', 'App\\Processor\\User\\ProfileProcessor', 'getProfileProcessorService', true],
            'App\\Processor\\User\\RegisterProcessor' => ['privates', 'App\\Processor\\User\\RegisterProcessor', 'getRegisterProcessorService', true],
            'App\\Processor\\User\\ResendVerificationProcessor' => ['privates', 'App\\Processor\\User\\ResendVerificationProcessor', 'getResendVerificationProcessorService', true],
            'App\\Processor\\User\\ResetPasswordConfirmProcessor' => ['privates', 'App\\Processor\\User\\ResetPasswordConfirmProcessor', 'getResetPasswordConfirmProcessorService', true],
            'App\\Processor\\User\\ResetPasswordRequestProcessor' => ['privates', 'App\\Processor\\User\\ResetPasswordRequestProcessor', 'getResetPasswordRequestProcessorService', true],
            'App\\Processor\\User\\VerifyProcessor' => ['privates', 'App\\Processor\\User\\VerifyProcessor', 'getVerifyProcessorService', true],
            'api_platform.doctrine.orm.state.persist_processor' => ['privates', 'api_platform.doctrine.orm.state.persist_processor', 'getApiPlatform_Doctrine_Orm_State_PersistProcessorService', true],
            'api_platform.doctrine.orm.state.remove_processor' => ['privates', 'api_platform.doctrine.orm.state.remove_processor', 'getApiPlatform_Doctrine_Orm_State_RemoveProcessorService', true],
            'api_platform.swagger_ui.processor' => ['privates', 'api_platform.swagger_ui.processor', 'getApiPlatform_SwaggerUi_ProcessorService', true],
        ], [
            'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor' => 'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor',
            'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor' => 'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor',
            'ApiPlatform\\Symfony\\Messenger\\Processor' => 'ApiPlatform\\Symfony\\Messenger\\Processor',
            'App\\Processor\\User\\ChangePasswordProcessor' => 'App\\Processor\\User\\ChangePasswordProcessor',
            'App\\Processor\\User\\ProfileProcessor' => 'App\\Processor\\User\\ProfileProcessor',
            'App\\Processor\\User\\RegisterProcessor' => 'App\\Processor\\User\\RegisterProcessor',
            'App\\Processor\\User\\ResendVerificationProcessor' => 'App\\Processor\\User\\ResendVerificationProcessor',
            'App\\Processor\\User\\ResetPasswordConfirmProcessor' => 'App\\Processor\\User\\ResetPasswordConfirmProcessor',
            'App\\Processor\\User\\ResetPasswordRequestProcessor' => 'App\\Processor\\User\\ResetPasswordRequestProcessor',
            'App\\Processor\\User\\VerifyProcessor' => 'App\\Processor\\User\\VerifyProcessor',
            'api_platform.doctrine.orm.state.persist_processor' => 'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor',
            'api_platform.doctrine.orm.state.remove_processor' => 'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor',
            'api_platform.swagger_ui.processor' => 'ApiPlatform\\Symfony\\Bundle\\SwaggerUi\\SwaggerUiProcessor',
        ]));
    }
}
