<?php

namespace Container871dO5O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_ApiPlatform_Openapi_Factory_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'lexik_jwt_authentication.api_platform.openapi.factory.inner' shared service.
     *
     * @return \ApiPlatform\OpenApi\Factory\OpenApiFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/openapi/Factory/OpenApiFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/openapi/Serializer/NormalizeOperationNameTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/openapi/Factory/TypeFactoryTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/openapi/Factory/OpenApiFactory.php';

        $a = ($container->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService($container));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'];
        }
        $b = ($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService($container));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'];
        }
        $c = ($container->privates['api_platform.json_schema.backward_compatible_schema_factory'] ?? $container->load('getApiPlatform_JsonSchema_BackwardCompatibleSchemaFactoryService'));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'];
        }
        $d = ($container->privates['api_platform.router'] ?? self::getApiPlatform_RouterService($container));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'];
        }

        return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory.inner'] = new \ApiPlatform\OpenApi\Factory\OpenApiFactory(($container->privates['api_platform.metadata.resource.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_NameCollectionFactory_CachedService($container)), $a, $b, ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? self::getApiPlatform_Metadata_Property_MetadataFactory_CachedService($container)), $c, ($container->privates['api_platform.filter_locator'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], [])), $container->parameters['api_platform.formats'], ($container->privates['api_platform.openapi.options'] ?? $container->load('getApiPlatform_Openapi_OptionsService')), ($container->privates['api_platform.pagination_options'] ?? $container->load('getApiPlatform_PaginationOptionsService')), $d, $container->parameters['api_platform.error_formats']);
    }
}
