<?php

namespace Container871dO5O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Processor\User\ProfileProcessor' shared autowired service.
     *
     * @return \App\Processor\User\ProfileProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Processor/User/ProfileProcessor.php';

        return $container->privates['App\\Processor\\User\\ProfileProcessor'] = new \App\Processor\User\ProfileProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
