<?php

namespace Container871dO5O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordConfirmProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Processor\User\ResetPasswordConfirmProcessor' shared autowired service.
     *
     * @return \App\Processor\User\ResetPasswordConfirmProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Processor/User/ResetPasswordConfirmProcessor.php';

        return $container->privates['App\\Processor\\User\\ResetPasswordConfirmProcessor'] = new \App\Processor\User\ResetPasswordConfirmProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
