<?php

namespace ContainerBGfxpEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAreaTimeSlotsProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Provider\Area\AreaTimeSlotsProvider' shared autowired service.
     *
     * @return \App\Provider\Area\AreaTimeSlotsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Provider/Area/AreaTimeSlotsProvider.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Provider\\Area\\AreaTimeSlotsProvider'])) {
            return $container->privates['App\\Provider\\Area\\AreaTimeSlotsProvider'];
        }

        return $container->privates['App\\Provider\\Area\\AreaTimeSlotsProvider'] = new \App\Provider\Area\AreaTimeSlotsProvider($a);
    }
}
