<?php

namespace ContainerBGfxpEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAreaCreateProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Processor\Area\AreaCreateProcessor' shared autowired service.
     *
     * @return \App\Processor\Area\AreaCreateProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Processor/Area/AreaCreateProcessor.php';

        return $container->privates['App\\Processor\\Area\\AreaCreateProcessor'] = new \App\Processor\Area\AreaCreateProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
