<?php

namespace ContainerBGfxpEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Provider\User\ProfileProvider' shared autowired service.
     *
     * @return \App\Provider\User\ProfileProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Provider/User/ProfileProvider.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Provider\\User\\ProfileProvider'])) {
            return $container->privates['App\\Provider\\User\\ProfileProvider'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Provider\\User\\ProfileProvider'])) {
            return $container->privates['App\\Provider\\User\\ProfileProvider'];
        }

        return $container->privates['App\\Provider\\User\\ProfileProvider'] = new \App\Provider\User\ProfileProvider($a, $b);
    }
}
