<?php

namespace ContainerBGfxpEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Processor\User\VerifyProcessor' shared autowired service.
     *
     * @return \App\Processor\User\VerifyProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Processor/User/VerifyProcessor.php';

        return $container->privates['App\\Processor\\User\\VerifyProcessor'] = new \App\Processor\User\VerifyProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
