<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSJAoR62\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSJAoR62/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSJAoR62.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSJAoR62\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerSJAoR62\App_KernelTestDebugContainer([
    'container.build_hash' => 'SJAoR62',
    'container.build_id' => '2353593a',
    'container.build_time' => 1767726691,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSJAoR62');
